### ISSUE TITLE
CreateBrowserContext returns code: -32000 msg: Not allowed

### ISSUE THREAD

**Issue by gpoetzelsberger** [wirepair/gcd#24]
Hi,
we are using gcd for our project, but since Chrome updated to version 71 calling CreateBrowserContext() gives us error code: -32000, msg: Not allowed.

Other projects similar to gcd may have a similar issue with the new Chrome release, like [here](https://github.com/mafredri/cdp/issues/80).

Any ideas what we could change for a quick fix? Thank you!

**Comment by wirepair** [comment]
Hmm that's odd it was working before? I tried locally in windows with chrome 71 and it did not work for me either.  Are you using headless, or for some reason can't just create new targets with debugger.NewTab()?

**Comment by wirepair** [comment]
So is there any way you can just use NewTab to get multiple tabs to do what you want instead of calling CreateBrowserContext? What in particular about createBrowserContext does your application need? Have you tried other devtool clients to see if any of them work? Actually, nevermind just came across this: https://github.com/chromedp/chromedp/issues/244. Seems like it's broken unfortunately.

**Comment by wirepair** [comment]
Closing this issue, feel free to reopen if there's something I can do on the gcd side of things.
